#!/usr/bin/env bash
#install ngix and put holberton inside

redi="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $redi" /etc/nginx/sites-available/default
sudo service nginx start
