#!/usr/bin/env bash
# install and setup HAPROXY

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernate/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*


echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 181854-web-01  check
   server 181854-web-02  check
" >> /etc/haproxy/haproxy.cfg
